export const BIBLE_BOOKS: Record<string, string> = {
  // Korean Names
  '창세기': 'GEN', '창': 'GEN', '창세': 'GEN',
  '출애굽기': 'EXO', '출': 'EXO', '출애': 'EXO',
  '레위기': 'LEV', '레': 'LEV', '레위': 'LEV',
  '민수기': 'NUM', '민': 'NUM', '민수': 'NUM',
  '신명기': 'DEU', '신': 'DEU', '신명': 'DEU',
  '여호수아': 'JOS', '수': 'JOS', '여호': 'JOS',
  '사사기': 'JDG', '삿': 'JDG', '사사': 'JDG',
  '룻기': 'RUT', '룻': 'RUT', '루기': 'RUT',
  '사무엘상': '1SA', '삼상': '1SA', '사무': '1SA',
  '사무엘하': '2SA', '삼하': '2SA',
  '열왕기상': '1KI', '왕상': '1KI', '열왕': '1KI', '왕': '1KI',
  '열왕기하': '2KI', '왕하': '2KI',
  '역대상': '1CH', '역상': '1CH', '대상': '1CH', '역대': '1CH',
  '역대하': '2CH', '역하': '2CH', '대하': '2CH',
  '에스라': 'EZR', '스': 'EZR', '에스': 'EZR',
  '느헤미야': 'NEH', '느': 'NEH', '느헤': 'NEH',
  '에스더': 'EST', '에': 'EST',
  '욥기': 'JOB', '욥': 'JOB',
  '시편': 'PSA', '시': 'PSA',
  '잠언': 'PRO', '잠': 'PRO',
  '전도서': 'ECC', '전': 'ECC', '전도': 'ECC',
  '아가': 'SNG', '아': 'SNG',
  '이사야': 'ISA', '사': 'ISA', '이사': 'ISA',
  '예레미야': 'JER', '렘': 'JER', '예레': 'JER',
  '예레미야애가': 'LAM', '애': 'LAM', '예레애': 'LAM',
  '에스겔': 'EZK', '겔': 'EZK',
  '다니엘': 'DAN', '단': 'DAN', '다니': 'DAN',
  '호세아': 'HOS', '호': 'HOS',
  '요엘': 'JOE', '욜': 'JOE',
  '아모스': 'AMO', '암': 'AMO',
  '오바댜': 'OBA', '옵': 'OBA',
  '요나': 'JON', '욘': 'JON',
  '미가': 'MIC', '미': 'MIC',
  '나훔': 'NAM', '나': 'NAM',
  '하박국': 'HAB', '합': 'HAB',
  '스바냐': 'ZEP', '습': 'ZEP',
  '학개': 'HAG', '학': 'HAG',
  '스가랴': 'ZEC', '슥': 'ZEC',
  '말라기': 'MAL', '말': 'MAL',
  '마태복음': 'MAT', '마': 'MAT', '마태': 'MAT',
  '마가복음': 'MRK', '막': 'MRK', '마가': 'MRK',
  '누가복음': 'LUK', '눅': 'LUK', '누': 'LUK', '누가': 'LUK',
  '요한복음': 'JHN', '요': 'JHN', '요한': 'JHN',
  '사도행전': 'ACT', '행': 'ACT', '사도': 'ACT',
  '로마서': 'ROM', '롬': 'ROM', '로마': 'ROM',
  '고린도전서': '1CO', '고전': '1CO', '고린도': '1CO',
  '고린도후서': '2CO', '고후': '2CO',
  '갈라디아서': 'GAL', '갈': 'GAL', '갈라': 'GAL',
  '에베소서': 'EPH', '엡': 'EPH', '에베': 'EPH',
  '빌립보서': 'PHP', '빌': 'PHP', '빌립': 'PHP',
  '골로새서': 'COL', '골': 'COL', '골로': 'COL',
  '데살로니가전서': '1TH', '살전': '1TH', '데살': '1TH',
  '데살로니가후서': '2TH', '살후': '2TH',
  '디모데전서': '1TI', '딤전': '1TI', '디모': '1TI',
  '디모데후서': '2TI', '딤후': '2TI',
  '디도서': 'TIT', '딛': 'TIT', '디도': 'TIT',
  '빌레몬서': 'PHM', '몬': 'PHM', '빌레': 'PHM',
  '히브리서': 'HEB', '히': 'HEB', '히브리어': 'HEB', '히브': 'HEB',
  '야고보서': 'JAS', '약': 'JAS', '야': 'JAS', '야고': 'JAS',
  '베드로전서': '1PE', '벧전': '1PE', '베드': '1PE',
  '베드로후서': '2PE', '벧후': '2PE',
  '요한1서': '1JN', '요일': '1JN',
  '요한2서': '2JN', '요이': '2JN',
  '요한3서': '3JN', '요삼': '3JN',
  '유다서': 'JUD', '유': 'JUD', '유다': 'JUD',
  '요한계시록': 'REV', '계': 'REV', '계시': 'REV',

  // English/Standard Codes (Support for New Version/새번역)
  // Extra English variants
  'Matt': 'MAT', 'Josh': 'JOS', 'Judg': 'JDG', 'Phile': 'PHM', 'Phlm': 'PHM', 'Hebr': 'HEB', 'Jam': 'JAS', '1Pet': '1PE', '2Pet': '2PE', '1Joh': '1JN', '2Joh': '2JN', '3Joh': '3JN', 'Revs': 'REV',
  // English Full names
  'Genesis': 'GEN', 'Exodus': 'EXO', 'Leviticus': 'LEV', 'Numbers': 'NUM', 'Deuteronomy': 'DEU',
  'Joshua': 'JOS', 'Judges': 'JDG', 'Ruth': 'RUT', '1 Samuel': '1SA', '2 Samuel': '2SA',
  '1 Kings': '1KI', '2 Kings': '2KI', '1 Chronicles': '1CH', '2 Chronicles': '2CH',
  'Ezra': 'EZR', 'Nehemiah': 'NEH', 'Esther': 'EST', 'Job': 'JOB', 'Psalms': 'PSA', 'Psalm': 'PSA',
  'Proverbs': 'PRO', 'Ecclesiastes': 'ECC', 'Song of Solomon': 'SNG', 'Isaiah': 'ISA',
  'Jeremiah': 'JER', 'Lamentations': 'LAM', 'Ezekiel': 'EZK', 'Daniel': 'DAN', 'Hosea': 'HOS',
  'Song of Songs': 'SNG', 'Songs': 'SNG', 'Canticles': 'SNG',
  'Joel': 'JOE', 'Amos': 'AMO', 'Obadiah': 'OBA', 'Jonah': 'JON', 'Micah': 'MIC', 'Nahum': 'NAM',
  'Habakkuk': 'HAB', 'Zephaniah': 'ZEP', 'Haggai': 'HAG', 'Zechariah': 'ZEC', 'Malachi': 'MAL',
  'Matthew': 'MAT', 'Mark': 'MRK', 'Luke': 'LUK', 'John': 'JHN', 'Acts': 'ACT', 'Romans': 'ROM',
  '1 Corinthians': '1CO', '2 Corinthians': '2CO', 'Galatians': 'GAL', 'Ephesians': 'EPH',
  'Philippians': 'PHP', 'Colossians': 'COL', '1 Thessalonians': '1TH', '2 Thessalonians': '2TH',
  '1 Timothy': '1TI', '2 Timothy': '2TI', 'Titus': 'TIT', 'Philemon': 'PHM', 'Hebrews': 'HEB',
  'James': 'JAS', '1 Peter': '1PE', '2 Peter': '2PE', '1 John': '1JN', '2 John': '2JN',
  '3 John': '3JN', 'Jude': 'JUD', 'Revelation': 'REV'
};

export const BIBLE_LIST = [
  { id: 'GEN', name: '창세기', chapters: 50 },
  { id: 'EXO', name: '출애굽기', chapters: 40 },
  { id: 'LEV', name: '레위기', chapters: 27 },
  { id: 'NUM', name: '민수기', chapters: 36 },
  { id: 'DEU', name: '신명기', chapters: 34 },
  { id: 'JOS', name: '여호수아', chapters: 24 },
  { id: 'JDG', name: '사사기', chapters: 21 },
  { id: 'RUT', name: '룻기', chapters: 4 },
  { id: '1SA', name: '사무엘상', chapters: 31 },
  { id: '2SA', name: '사무엘하', chapters: 24 },
  { id: '1KI', name: '열왕기상', chapters: 22 },
  { id: '2KI', name: '열왕기하', chapters: 25 },
  { id: '1CH', name: '역대상', chapters: 29 },
  { id: '2CH', name: '역대하', chapters: 36 },
  { id: 'EZR', name: '에스라', chapters: 10 },
  { id: 'NEH', name: '느헤미야', chapters: 13 },
  { id: 'EST', name: '에스더', chapters: 10 },
  { id: 'JOB', name: '욥기', chapters: 42 },
  { id: 'PSA', name: '시편', chapters: 150 },
  { id: 'PRO', name: '잠언', chapters: 31 },
  { id: 'ECC', name: '전도서', chapters: 12 },
  { id: 'SNG', name: '아가', chapters: 8 },
  { id: 'ISA', name: '이사야', chapters: 66 },
  { id: 'JER', name: '예레미야', chapters: 52 },
  { id: 'LAM', name: '예레미야애가', chapters: 5 },
  { id: 'EZK', name: '에스겔', chapters: 48 },
  { id: 'DAN', name: '다니엘', chapters: 12 },
  { id: 'HOS', name: '호세아', chapters: 14 },
  { id: 'JOE', name: '요엘', chapters: 3 },
  { id: 'AMO', name: '아모스', chapters: 9 },
  { id: 'OBA', name: '오바댜', chapters: 1 },
  { id: 'JON', name: '요나', chapters: 4 },
  { id: 'MIC', name: '미가', chapters: 7 },
  { id: 'NAM', name: '나훔', chapters: 3 },
  { id: 'HAB', name: '하박국', chapters: 3 },
  { id: 'ZEP', name: '스바냐', chapters: 3 },
  { id: 'HAG', name: '학개', chapters: 2 },
  { id: 'ZEC', name: '스가랴', chapters: 14 },
  { id: 'MAL', name: '말라기', chapters: 4 },
  { id: 'MAT', name: '마태복음', chapters: 28 },
  { id: 'MRK', name: '마가복음', chapters: 16 },
  { id: 'LUK', name: '누가복음', chapters: 24 },
  { id: 'JHN', name: '요한복음', chapters: 21 },
  { id: 'ACT', name: '사도행전', chapters: 28 },
  { id: 'ROM', name: '로마서', chapters: 16 },
  { id: '1CO', name: '고린도전서', chapters: 16 },
  { id: '2CO', name: '고린도후서', chapters: 13 },
  { id: 'GAL', name: '갈라디아서', chapters: 6 },
  { id: 'EPH', name: '에베소서', chapters: 6 },
  { id: 'PHP', name: '빌립보서', chapters: 4 },
  { id: 'COL', name: '골로새서', chapters: 4 },
  { id: '1TH', name: '데살로니가전서', chapters: 5 },
  { id: '2TH', name: '데살로니가후서', chapters: 3 },
  { id: '1TI', name: '디모데전서', chapters: 6 },
  { id: '2TI', name: '디모데후서', chapters: 4 },
  { id: 'TIT', name: '디도서', chapters: 3 },
  { id: 'PHM', name: '빌레몬서', chapters: 1 },
  { id: 'HEB', name: '히브리서', chapters: 13 },
  { id: 'JAS', name: '야고보서', chapters: 5 },
  { id: '1PE', name: '베드로전서', chapters: 5 },
  { id: '2PE', name: '베드로후서', chapters: 3 },
  { id: '1JN', name: '요한1서', chapters: 5 },
  { id: '2JN', name: '요한2서', chapters: 1 },
  { id: '3JN', name: '요한3서', chapters: 1 },
  { id: 'JUD', name: '유다서', chapters: 1 },
  { id: 'REV', name: '요한계시록', chapters: 22 }
];
